### ISSUE TITLE
XLIFF-Dateistruktur wird von Trados nicht richtig unterstützt

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-xliff#14]
Es gibt Probleme mit den Zeilenumbrüchen: vorher waren sie mit <br class="xliff-newline" /> normalisiert, jetzt sind das einfach Zeilenumbrüche und das zerstückelt den Text in Trados.
Außerdem stimmt etwas mit der Zeichenkodierung nicht - das soll UTF-8 sein, aber lässt sich nicht konvertieren und verhindert die Text-Vorschau in unserem Tool. Das Einfügen von <?xml version="1.0" encoding="utf-8" standalone="no"?> in die Dateien hilft auch nicht, dass die Umlaute danach korrekt angezeigt werden.

**Comment by wrcg** [comment]
Ergänzung: Der Code im RRZE-Plugin ist noch in Ordnung (xliff-download.php), das ist also nicht das Problem. Das Problem ist entstanden, da die Dateistruktur geändert wurde. Wir haben jetzt xliff 2.0 mit einer anderen Struktur bekommen. Wenn dies rückgängig gemacht werden könnte, dann müsste es wieder wie vorher funktionieren.

**Comment by xwolfde** [comment]
In #15 ausformuliert
