### ISSUE TITLE
Konfiguration

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-xliff#4]
Folgende Anforderungen soll die Konfiguration erfüllen:
* Die Konfiguration soll erreichbar sein für lokale Siteadministratoren.
* Die Konfig wird im Backend unter Werkzeuge / Tools eingeordnet

Folgende Einstellungen sollen möglich sein:
* Export-Funktionen: 
    * E-Mail-Adresse für automatische Versendung der XLIFF-Datei
    * E-Mail-Subjekt als Template mit  Variablen für die Post-ID, Post-Title, Zielsprache 
    * Angabe der MIndestrolle für die Export-Funktion
  
    Die XLIFF-Datei soll grundsätzlich im XLIFF2-Format gespeichert werden. Die Datei soll das unten angegebene Dateinamensformat haben.

* Allgemeines:
    * SIchtbarkeit von Export/Import-Funktionen: Angabe der Mindestrolle ausgehend aus der Liste der vorhandenen Rollen im System
    * Auswahl der Post-Types für die die Import/Export-Funktion bereitgestellt wird
   * Einstellung der Felder aus dem Post-Type, die als zu übersetzender Text Teil der XLIFF sein sollen. Per Default: Title, Excerpt, Content, sowie die Caption-Texte von allen angehängten Attachments des Post-Types
* Mehrfach-Export
    * Angabe der maximalen Zahl an möglichen Datei-Anhängen (XLIFF-Dateien) pro E-Mail

**Comment by rvdforst** [comment]
Um eine Seite oder einen Beitrag in einer WP-Multisite-Installation eindeutig zu identifizieren, empfehle ich das folgende Format für den Namen der XLIFF-Dateien:
domain-path-slug-postid-yy-mm-dd.xliff

**Comment by xwolfde** [comment]
Hm... $domain-$path kann bei komplexen Sites recht groß werden und Path wird nicht unbedingt gebraucht, wenn man ja doch die Id des Objekts hat. Wäre nicht 
$SiteID-$Posttype-$PostId-yy-mm-dd.xliff
ausreichend?
Der Upload erfolgt ja sowieso (erstmal) nur über das Backend von einem in der SIte angemeldeten Menschen.

Später, wenn wir was automatisieren wollten, dann bräuchte man die $SiteId .

**Comment by rvdforst** [comment]
Das Plugin muss auch Multisites mit Unterverzeichnissen (bspw. blogs.fau.de/career) unterstützen. Wenn die Multisite auf Subdomains basiert, wird den Path nicht verwendet. Die Blog-ID allein macht den Dateinamen nicht eindeutig. Wofür ist den Post-Type? Vorschlag:

domain[-path]-blogid-postid-yymmdd.xliff

site_id != blog_id

**Comment by xwolfde** [comment]
Nach Diskussion:
* $domain = aktueller Domainname (Hauptdomain), wie bspw. www.fau.de bei einer Domainbased Instanz
* $path = Directory bei einer Directory-based Instanz, ansonsten entfällt dieser Eintrag (inkl. "-").
* $BlogId = Die Id der Website in der Multisiteinstanz (blog_id). Wenn keine Multisiteinstanz = 1.
* $PostId = Id des Objects unabhängig davon, welcher Post Type es ist
* $Datum = Im Format (ohne "-"): YYYYMMDD

Somit also als Beispiel bei einer domainbased Multisite:
```www.fau.de-2-123-20181127.xliff```

Beispiel für eine directory based Installation:
```www.blogs.fau.de-webworking-8-24333-20181127.xliff```

**Comment by xwolfde** [comment]
passt
